name: apiget
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  google_fonts : 6.1.0
  flutter_screenutil : ^5.0.1
  get: 4.6.6
  stroke_text: ^0.0.2
  flutter: 
    sdk: flutter
  cached_network_image : ^3.3.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

